variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_token" {}
variable "aws_db_username" {}
variable "aws_db_password" {}
variable "gitlab_deploy_token_username" {}
variable "gitlab_deploy_token_token" {}
variable "gitlab_access_token" {}
#variable "backend_arn" {aws_ecs_task_definition.ecs_task_definition_backend.arn}
variable "api_key_fastapi" {}
variable "s3_bucket" {}
